### ISSUE TITLE
[BUG] Unable to recover transaction

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#36]
**Describe the bug**
We are currently unable to use the 'recover' feature of Victoria Email

**To Reproduce**
1. victoria email recover dev -i id.txt -o smtp.domain.com (please speak to @AshKapow for transaction and endpoint details)

**Expected behavior**
Email is recovered and played through the platform

**CLI output**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 184, in recover
    recover_mail.recover(cfg.mail_toil, cluster, input, output, cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/recover_mail.py", line 38, in recover
    blob_client = blob_storage.connect(cfg.get_storage_account(cluster))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/blob_storage.py", line 32, in connect
    return BlobServiceClient.from_connection_string(connection_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/storage/blob/_blob_service_client.py", line 164, in from_connection_string
    account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 349, in parse_connection_str
    conn_str = conn_str.rstrip(";")
AttributeError: 'EncryptionEnvelope' object has no attribute 'rstrip'
```

**Acceptance criteria**
Able to 'recover' an email based on a text file of transaction IDs
Able to 'recover' an email based on a single transaction ID
Update the Help text with the new functionality

**Comment by mukulgupta2138** [comment]
Based on discussion, we want following:

- Fix the current bug to enable recover functionality with plain texts
- Fix the plain text usage to actual encryption strings.

**Comment by mukulgupta2138** [comment]
Fix has been merged into master. Closing this issue.
