### ISSUE TITLE
[BUG] Unable to Reconstruct - Connection string missing required connection details

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#37]
**Describe the bug**

**To Reproduce**
1. `victoria email reconstruct dev -i xxx -o reconstructed` (please speak to @AshKapow for transaction and endpoint details)

**Acceptance criteria**
Able to 'reconstruct' an email based on a text file of transaction IDs
Able to 'reconstruct' an email based on a single transaction ID
Update the Help text with the new functionality

**CLI output**
```
Connecting to blob storage for 'dev'...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 385, in parse_connection_str
    conn_settings["AccountName"], service, conn_settings.get("EndpointSuffix", SERVICE_HOST_BASE)
KeyError: 'AccountName'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 139, in reconstruct
    transaction_id, anon, cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/reconstruct_mail.py", line 82, in reconstruct
    blob_client = blob_storage.connect(storage_conn_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/blob_storage.py", line 32, in connect
    return BlobServiceClient.from_connection_string(connection_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/storage/blob/_blob_service_client.py", line 164, in from_connection_string
    account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/storage/blob/_shared/base_client.py", line 388, in parse_connection_str
    raise ValueError("Connection string missing required connection details.")
ValueError: Connection string missing required connection details.

```

**Comment by mukulgupta2138** [comment]
@AshKapow Created a PR for this https://github.com/glasswall-sre/victoria_email/pull/49

**Comment by AshKapow** [comment]
Confirm that this resolves the issue

**Comment by mukulgupta2138** [comment]
Closing this issue
