### ISSUE TITLE
[BUG] Replay function not working

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#42]
**Describe the bug**
When running the Replay function, it should replay an email from Azure Service Bus Queues and back into the Rebuild for Email platform. 

**To Reproduce**
1. Have valid Victoria config (speak to @AshKapow)
2. Run this command `victoria email replay dev`

**CLI output**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 153, in replay
    replay_deadletters.replay(cfg.mail_toil, cluster, cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/replay_deadletters.py", line 60, in replay
    cfg.get_service_bus_connection_str(cluster))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/encryption/provider.py", line 79, in decrypt_str
    decrypted = self.decrypt(envelope)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/encryption/azure_provider.py", line 107, in decrypt
    if envelope.version != self.key_encryption_key.properties.version:
AttributeError: 'str' object has no attribute 'version'
```

**Platform:**
 - OS: MacOS
 - Shell: Bash
 - Python version: 3.7

**Comment by mukulgupta2138** [comment]
Created a PR around this https://github.com/glasswall-sre/victoria_email/pull/45

**Comment by mukulgupta2138** [comment]
This is now fixed, closing the issue
