### ISSUE TITLE
[BUG] Send function not working

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#44]
**Describe the bug**
When running the Send function, it should send an email/emails to an SMTP endpoint. 

**To Reproduce**
1. Have valid Victoria config (speak to @AshKapow)
2. Run this command `victoria email send send_dev.txt`

**CLI output**
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 212, in send
    send_mail.send_manifest(loaded_manifest)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/send_mail.py", line 118, in send_manifest
    smtp.send(msg, smtp_url)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sremail/smtp.py", line 50, in send
    with smtplib.SMTP(smtp_url, timeout=timeout) as smtp:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out
```

**Platform:**
 - OS: MacOS
 - Shell: Bash
 - Python version: 3.7

**Comment by mukulgupta2138** [comment]
As discussed with @AshKapow this is working fine. The issue was with smtp address which was not valid. Closing this one.
