### ISSUE TITLE
[BUG] Unable to Loadtest with Encrypted Connection Strings

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#54]
**Describe the bug**
After the implementation of encrypted connection strings in #53 we are now getting issues with the loadtest function

**To Reproduce**
1. `victoria email loadtest -e smtp.domain.com -i *** -r test@glasswallsolutions.com -s test@glasswallsolutions.com`

**CLI output** 
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 101, in loadtest
    sender, tenant_ids, cfg.load_test))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/load_test.py", line 128, in perform_load_test
    distributions = Distribution.get_random_distributions(load_test_config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/schemas.py", line 137, in get_random_distributions
    properties = get_blob_properties('fileattachments', conn_str)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/blob_storage.py", line 76, in get_blob_properties
    return get_container(container_name, connection_str).list_blobs()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/blob_storage.py", line 72, in get_container
    return connect(connection_str).get_container_client(container_name)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/blob_storage.py", line 32, in connect
    return BlobServiceClient.from_connection_string(connection_str.replace(';;', ';'))
AttributeError: 'EncryptionEnvelope' object has no attribute 'replace'
```

**Platform:**
 - OS: Mac OS
 - Shell: Terminal
 - Victoria version: v0.6.6
 - Python version: 3.7

**Comment by mukulgupta2138** [comment]
@AshKapow Created a PR for this https://github.com/glasswall-sre/victoria_email/pull/55
