### ISSUE TITLE
[BUG] Reconstruct 'list' Failure

### ISSUE THREAD

**Issue by AshKapow** [glasswall-sre/victoria_email#59]
**Describe the bug**
When attempting to reconstruct 'some' emails, it's failing with the below error, this needs to be investigated

**To Reproduce**
Steps to reproduce the behaviour:
1. `victoria email reconstruct client -id $_.TransactionID -o $output`

**Expected behaviour**
Successful rebuild of email, including attachments

**CLI output**
```
Connecting to blob storage for 'client'...
--> Processing message for transaction '***'
    Writing message '***.eml'
    Writing email body '***_html.html'
    Writing attachment '***.png'
    Writing attachment '***_None'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/victoria", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria/script/victoria.py", line 108, in main
    cli.main(obj=cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/__init__.py", line 139, in reconstruct
    transaction_id, anon, cfg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/reconstruct_mail.py", line 92, in reconstruct
    output_dir, anonymise)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/mail_reconstruction.py", line 174, in process_mime_message
    write_mime_message_payloads(output_dir, transaction_id, parsed_msg)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/mail_reconstruction.py", line 151, in write_mime_message_payloads
    write_attachment(output_dir, transaction_id, part)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/victoria_email/core/mail_reconstruction.py", line 74, in write_attachment
    decoded = base64.b64decode(part.get_payload())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 80, in b64decode
    s = _bytes_from_decode_data(s)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'list'
```

**Platform:**
 - OS: Mac OS Big Sur
 - Shell: Powershell
 - Victoria version: v0.8.5
 - Python version: v3.7

**Comment by mukulgupta2138** [comment]
This is now fixed, marking as closed.
